# Generated by Django 3.0 on 2020-06-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
